#!/bin/bash
#SBATCH -t 3-00:00:00
#SBATCH -p normal
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

inp_dir=$1
out_path=$2

echo "" > $out_path # clear

counter=0
for model_path in $(ls $inp_dir/*.pkl)
do
    attack=SPSA
    python -u adversarial.py --dataset=mnist --attack=$attack --report_interval=10 \
            --model_path=$model_path --json_out_path=$out_path --nb_iter=50 --num_batches=10 &
    ((counter++))
    if [ $counter == 4 ]; then
        wait
        counter=0
    fi
done
wait