#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

mkdir -p output/debug

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    python -u train.py cifar-10 --vgg_name='VGG11' --use_batchnorm=True --modification_start_layer=0 $second_param_onwards &> output/debug/$name.log
}

train debugging-relu --device=cuda:0 &
train debugging-relu-elliptical --device=cuda:1 --use_elliptical --curvature_multiplier_start=0.05 --curvature_multiplier_stop=0.05 --n_epochs=80 &
wait

echo -n "Finished: " && date
