#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    # use this for testing: --vgg_name=VGG4 
    python -u train.py cifar-10 --vgg_name=VGG16 --use_batchnorm=True --modification_start_layer=12 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

# Notice: can't share this part with mnist because some params are different
# Notice: don't use "\" to put parameters on the next line, the method will ignore them...
train relu --device=cuda:0 &
train relog --device=cuda:1 --use_relog=True &
wait

train relog-maxout_4 --device=cuda:0 --use_relog=True --use_maxout=max --max_folding_factor=4 &
train relog-minmaxout_2_4 --device=cuda:1 --use_relog=True --use_maxout=minmax --max_folding_factor=4 --min_folding_factor=2 &
wait

train relog-minmaxout_2_4-max_fit_l2 --device=cuda:1 --use_relog=True --use_maxout=minmax --max_folding_factor=4 --min_folding_factor=2 --regularization=max-fit --l2=0.01 --bias_l2=0.01 &
wait

echo -n "Finished: " && date
