#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    # use this for testing: --vgg_name=VGG4 
    python -u train.py cifar-10 --vgg_name=VGG16 --use_batchnorm=True --modification_start_layer=12 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

train relog-elliptical --device=cuda:0 --use_relog=True --use_elliptical=True --capacity_factor=2 &
train relog-elliptical-max_fit_l1 --device=cuda:0 --use_relog=True --use_elliptical=True --regularization=max-fit --l1=0.01 --bias_l1=0.01 --capacity_factor=2 &
wait 

train relog-elliptical-max_fit_l1-mse --device=cuda:0 --use_relog=True --use_elliptical=True --regularization=max-fit --l1=0.01 --bias_l1=0.01 --use_mse=True --capacity_factor=2 &
train relog-elliptical-max_fit_l1-mse-overlay --device=cuda:0 --use_relog=True --use_elliptical=True --regularization=max-fit --l1=0.01 --bias_l1=0.01 --use_mse=True --use_overlay=True --capacity_factor=2 &
wait

echo -n "Finished: " && date
