#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate
. scripts/cifar10-common.sh

echo -n "Started: " && date

(train relog-maxout-elliptical --device=cuda:0 $relog_conf $maxout_conf $elliptical_conf ; \
 train relog-maxout-elliptical-maxfit-bce --device=cuda:0 $relog_conf $maxout_conf $elliptical_conf $maxfit_conf $bce_conf) &

(train relog-maxout-elliptical-maxfit --device=cuda:1 $relog_conf $maxout_conf $elliptical_conf $maxfit_conf ; \
 train relog-maxout-elliptical-maxfit-bce-overlay --device=cuda:1 $relog_conf $maxout_conf $elliptical_conf $maxfit_conf $bce_conf --use_overlay=True) &
 
wait

echo -n "Finished: " && date
