#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    python -u train.py cifar-10 --vgg_name=VGG11 --use_batchnorm=True --modification_start_layer=0 --n_epochs=80 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

relog_conf="--use_relog=True --log_strength_start=-0.4 --log_strength_inc=0.0001"
elliptical_conf="--use_elliptical=True --curvature_multiplier_start=-0.5 --curvature_multiplier_stop=1"
maxout_conf="--use_maxout=max --max_folding_factor=4"
maxfit_conf="--regularization=max-fit --l1=1 --bias_l1=1 --regularization_start_epoch=52"

# Notice: can't share this part with mnist because some params are different
# Notice: don't use "\" to put parameters on the next line, the method will ignore them...
train relu --device=cuda:0 &
train relog --device=cuda:1 $relog_conf &
wait

train relog-elliptical --device=cuda:0 $relog_conf $elliptical_conf &
train relog-elliptical-maxout-maxfit_l1 --device=cuda:1 $relog_conf $elliptical_conf $maxout_conf $maxfit_conf &
wait

echo -n "Finished: " && date
