#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    # use this for testing: --vgg_name=VGG4 
    python -u train.py cifar-10 --vgg_name=VGG11 --use_batchnorm=True --modification_start_layer=0 --n_epochs=80 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

. scripts/cifar10-common.sh

(train relog-elliptical --device=cuda:0 $relog_conf $elliptical_conf ; \
 train relog-elliptical-maxfit --device=cuda:0 $relog_conf $elliptical_conf $maxfit_conf) &
train relog-elliptical-maxout-maxfit_l1 --device=cuda:1 $relog_conf $elliptical_conf $maxout_conf $maxfit_conf &
wait

echo -n "Finished: " && date
