#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    # use this for testing: --vgg_name=VGG4 
    python -u train.py cifar-10 --vgg_name=VGG11 --use_batchnorm=True --modification_start_layer=0 --n_epochs=80 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

. scripts/cifar10-common.sh
maxfit_conf="--regularization=max-fit --l1=0.05 --bias_l1=0.1 --regularization_start_epoch=52" # otherwise, training would collapse

train relog-maxout-elliptical-max_fit_l1-mse --device=cuda:0 $relog_conf $elliptical_conf $maxout_conf $maxfit_conf $mse_conf &
train relog-maxout-elliptical-max_fit_l1-mse-overlay --device=cuda:1 $relog_conf $elliptical_conf $maxout_conf $maxfit_conf $mse_conf --use_overlay=True &
wait

echo -n "Finished: " && date
