#!/bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    python -u train.py mnist --n_epochs=20 --lr=0.001 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

# don't use "\" to put parameters on the next line, the method will ignore them...
train relu --device=cuda:0 &
train relog --device=cuda:1 --use_relog=True &
wait

train relog-maxout_4 --device=cuda:0 --use_relog=True --use_maxout=max --max_folding_factor=4 &
train relog-minmaxout_2_4 --device=cuda:1 --use_relog=True --use_maxout=minmax --max_folding_factor=4 --min_folding_factor=2 &
wait

train relog-elliptical-maxout_4 --device=cuda:1 --use_relog=True --use_elliptical=True --use_maxout=max --max_folding_factor=4 &
train relog-elliptical-maxout_4-max_fit_l1_1 --device=cuda:0 --use_relog=True --use_elliptical=True --use_maxout=max --max_folding_factor=4 --regularization=max-fit --bias_l1=1 --l1=1 &
wait

train relog-elliptical-maxout_4-sigmoid_out-max_fit_l1_1 --device=cuda:0 --use_relog=True --use_elliptical=True --use_sigmoid_out=True --use_maxout=max --max_folding_factor=4 --regularization=max-fit --bias_l1=1 --l1=1 &
train relog-elliptical-maxout_4-sigmoid_out-max_fit_l1_1-scrambling --device=cuda:1 --use_relog=True --use_elliptical=True --use_sigmoid_out=True --use_maxout=max --max_folding_factor=4 --regularization=max-fit --bias_l1=1 --l1=1 --use_scrambling=True &
wait

echo -n "Finished: " && date
