#!/bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -p gpu
#SBATCH --export=NONE

. scripts/init-cartesius.sh
. venv/bin/activate

echo -n "Started: " && date

out_dir=$1

train() {
    name=$1
    second_param_onwards="${@:2}"
    echo "Training $name"
    # use this for testing: --vgg_name=VGG4 
    python -u train.py cifar-10 --vgg_name=VGG11 --use_batchnorm=True --elliptical_stop=1 --modification_start_layer=0 --n_epochs=80 --out_path=$out_dir/$name.pkl $second_param_onwards &> $out_dir/$name.log
}

relog_conf="--use_relog=True --log_strength_start=-0.8 --log_strength_inc=0.0001 --log_strength_stop=1"
elliptical_conf="--use_elliptical=True --elliptical_stop=1 --curvature_multiplier_start=-0.4 --curvature_multiplier_stop=1"
maxout_conf="--use_maxout=max --max_folding_factor=4"
minmaxout_conf="--use_maxout=minmax --min_folding_factor=2 --max_folding_factor=4"
maxfit_conf="--regularization=max-fit --l1=1 --bias_l1=0.1 --regularization_start_epoch=0"
mse_conf="--use_mse=True --mse_weighted=False"

# (train relog-minmaxout-elliptical_stop1 --device=cuda:0 $relog_conf $minmaxout_conf $elliptical_conf ; \
#  train relog-minmaxout-elliptical_stop1-maxfit --device=cuda:0 $relog_conf $minmaxout_conf $elliptical_conf $maxfit_conf ;\
#  train relog-minmaxout-elliptical_stop1-maxfit-mse --device=cuda:0 $relog_conf $minmaxout_conf $elliptical_conf $maxfit_conf $mse_conf) &
# (train relog-maxout --device=cuda:1 $relog_conf $maxout_conf; \
#  train relog-minmaxout --device=cuda:1 $relog_conf $minmaxout_conf; \
#  train relog-minmaxout-elliptical_stop1-maxfit-mse-overlay --device=cuda:1 $relog_conf $minmaxout_conf $elliptical_conf $maxfit_conf $mse_conf --use_overlay=True)&
# wait

(train relog-minmaxout-elliptical_stop1-maxfit --device=cuda:0 $relog_conf $minmaxout_conf $elliptical_conf $maxfit_conf ;\
 train relog-minmaxout-elliptical_stop1-maxfit-mse --device=cuda:0 $relog_conf $minmaxout_conf $elliptical_conf $maxfit_conf $mse_conf) &
(train relog-minmaxout-elliptical_stop1-maxfit-mse-overlay --device=cuda:1 $relog_conf $minmaxout_conf $elliptical_conf $maxfit_conf $mse_conf --use_overlay=True) &
wait

echo -n "Finished: " && date
